// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OmniView._2019
{
    internal sealed partial class Vsix
    {
        public const string Id = "OmniView.MISoftware.e3a6c7fb-0320-4655-9a97-afdf58c57fa3";
        public const string Name = "OmniView for VS2019";
        public const string Description = @"Provides a previewer margin to the HTML editor, allowing you to instantly see the output of Sciter HTML page";
        public const string Language = "en-US";
        public const string Version = "2.18";
        public const string Author = "MI Software";
        public const string Tags = "Sciter, HTML, CSS";
    }
}
