// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniView
{
	static class Vsix
	{
		public const string Id = "OmniView.MISoftware.e3a6c7fb-0320-4655-9a97-afdf58c57fad";
		public const string Name = "OmniView";
		public const string Description = @"Provides a previewer margin to the HTML editor, allowing you to instantly see the output of Sciter HTML page.";
		public const string Language = "en-US";
		public const string Version = "2.6";
		public const string Author = "MI Software";
		public const string Tags = "Sciter, HTML, CSS";
	}
}
