// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OmniView
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GUID_OmniViewPackageString = "4bfa7cef-9c74-45a6-93ba-8e6a405e71e7";
        public static Guid GUID_OmniViewPackage = new Guid(GUID_OmniViewPackageString);

        public const string GUID_CmdSetString = "1413ba08-4c40-4919-831b-09ad68f847f9";
        public static Guid GUID_CmdSet = new Guid(GUID_CmdSetString);

        public const string GUID_CmdOmniViewString = "15abb72b-1241-4c5c-93b8-e9354592367e";
        public static Guid GUID_CmdOmniView = new Guid(GUID_CmdOmniViewString);

        public const string guidTextEditorString = "8b382828-6202-11d1-8870-0000f87579d2";
        public static Guid guidTextEditor = new Guid(guidTextEditorString);

        public const string guidHtmlEditorString = "c76d83f8-a489-11d0-8195-00a0c91bbee3";
        public static Guid guidHtmlEditor = new Guid(guidHtmlEditorString);

        public const string guidHtmlEditorFactoryString = "40d31677-cbc0-4297-a9ef-89d907823a98";
        public static Guid guidHtmlEditorFactory = new Guid(guidHtmlEditorFactoryString);

        public const string guidWebFormsEditorString = "57312c73-6202-49e9-b1e1-40ea1a6dc1f6";
        public static Guid guidWebFormsEditor = new Guid(guidWebFormsEditorString);

        public const string htmlEditorCommandSetString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid htmlEditorCommandSet = new Guid(htmlEditorCommandSetString);

        public const string htmlEditorCommandSetLibraString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid htmlEditorCommandSetLibra = new Guid(htmlEditorCommandSetLibraString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ID_Group = 0x0100;
        public const int ID_CmdToggleOmniView = 0x0101;
        public const int ID_CmdToggleConsole = 0x0102;
        public const int htmlContextMenu = 0x0033;
        public const int htmlContextMenuLibra = 0x0001;
    }
}